# Generated by Django 5.2.5 on 2025-09-07 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('homeworks_submitted', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('password', models.CharField(max_length=255, verbose_name='Paroli')),
                ('category', models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=20, verbose_name='Kategoriyasi')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='lessons/videos/')),
                ('description', models.TextField()),
                ('note', models.FileField(blank=True, null=True, upload_to='lessons/notes/')),
                ('homework', models.FileField(blank=True, null=True, upload_to='lessons/homeworks/')),
                ('date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='blog.group')),
                ('lesson_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='blog.lesson_group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'category': 'Student'}, related_name='student_groups', to='blog.worker'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'category': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='blog.worker'),
        ),
    ]
