# Generated by Django 5.2.5 on 2025-09-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.FileField(null=True, upload_to='lessons/homeworks/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='note',
            field=models.FileField(null=True, upload_to='lessons/notes/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(null=True, upload_to='lessons/videos/'),
        ),
    ]
