# Generated by Django 5.2.5 on 2025-09-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_lesson_description_alter_lesson_homework_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_group',
            name='modul',
            field=models.IntegerField(default=1),
        ),
    ]
