# Generated by Django 5.2.5 on 2025-09-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_lesson_group_modul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_group',
            name='modul',
        ),
        migrations.AddField(
            model_name='lesson',
            name='modul',
            field=models.IntegerField(default=1),
        ),
    ]
