# Generated by Django 5.2.5 on 2025-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_lesson_group_modul_lesson_modul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.AddField(
            model_name='lesson_group',
            name='groups',
            field=models.ManyToManyField(related_name='lessons', to='blog.group'),
        ),
    ]
