# Generated by Django 5.2.5 on 2025-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_lesson_group_lesson_group_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.FileField(blank=True, null=True, upload_to='lessons/homeworks/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='note',
            field=models.FileField(blank=True, null=True, upload_to='lessons/notes/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/'),
        ),
    ]
