# Generated by Django 5.2.5 on 2025-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_lesson_lesson_number_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_group',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'category': 'Teacher'}, related_name='teacher_groups', to='blog.worker'),
        ),
    ]
